### ISSUE TITLE
Authorship

### ISSUE THREAD

**Issue by varund7726** [CypherOS/frameworks_base#1]
Sorry to do open an issue like this but had no other place to comment 
The authorship of this commit is wrong

https://github.com/CypherOS/frameworks_base/commit/f758e45f8c5c4b5bb2fa29c754a7fe9fd7346779

Please provide proper authorship and also go the original author of dynamic navbar colors
Dynamic navbar

https://github.com/ResurrectionRemix/android_frameworks_base/commit/3e498b98da2fad742ca4c04bb4c4aaa39d7f6386
Switch

https://github.com/ResurrectionRemix/android_frameworks_base/commit/ab8fa403f5e18e54b0947ceea482fac1e7365336

Thanks

**Comment by Sirhc95** [comment]
I know, got the emails mixed up on gerrit. Working on it

**Comment by varund7726** [comment]
Thanks man .appreciate it
